=== VeroLedesma/RETOLMS/XML/tienda.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tienda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="juegos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="juego" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="descripcion" type="xs:string" minOccurs="0"/>
                                        <xs:element name="genero" type="generosType" />
                                        <xs:element name="precio" type="xs:string"/>
                                        <xs:element name="tipo">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="2D"/>
                                                    <xs:enumeration value="3D"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
<<<<<<< HEAD
=======
                                        <xs:element name="categoria" type="categoriasType"/>
>>>>>>> eb8a0721894bf1a1ce89b4d3af93bf36aaf1ac21
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[A-Z][0-9]{3}"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="publicado" type="xs:boolean" use="optional" default="false"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
<<<<<<< HEAD
=======
                <xs:element name="categorias">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="categoria" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Nacional"/>
                                        <xs:enumeration value="Internacional"/>
                                       
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
>>>>>>> eb8a0721894bf1a1ce89b4d3af93bf36aaf1ac21
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="generosType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Accion"/>
            <xs:enumeration value="Aventura"/>
            <xs:enumeration value="Carreras"/>
<<<<<<< HEAD
            <xs:enumeration value="Sandbox"/>
            <xs:enumeration value="Role-Playing"/>
            <xs:enumeration value="Estrategia"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>
=======
            <xs:enumeration value="Deportes"/>
            <xs:enumeration value="Estrategia"/>
            <xs:enumeration value="Simulacion"/>
            <xs:enumeration value="Rol"/>
            <xs:enumeration value="Puzzle"/>
            <xs:enumeration value="Musical"/>
            <xs:enumeration value="Plataformas"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="categoriasType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Nacional"/>
            <xs:enumeration value="Internacional"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>
>>>>>>> eb8a0721894bf1a1ce89b4d3af93bf36aaf1ac21

=== VeroLedesma/RETOLMS/XML/tienda.xml
<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tienda.xsd">
    <juegos>
        <juego id="A001" publicado="true">
            <nombre>Animal Crossing</nombre>
            <descripcion> Descripción del juego </descripcion>
            <genero>Role-Playing</genero>
            <precio>30</precio>
            <tipo>3D</tipo>
=======
<tienda>
     <!-- Información de los juegos -->
    <juegos>
        <juego id="A001" publicado="true">
            <nombre>Animal Crossing</nombre>
            <descripcion>Descripción del juego</descripcion>
            <genero>Accion</genero>
            <precio>30</precio>
            <tipo>3D</tipo>
            <categoria>01</categoria>
>>>>>>> eb8a0721894bf1a1ce89b4d3af93bf36aaf1ac21
        </juego>

        <juego id="B002" publicado="true">
            <nombre>Zelda</nombre>
<<<<<<< HEAD
            <descripcion> Descripción del juego </descripcion>
            <genero>Aventura</genero>
            <precio>80</precio>
            <tipo>2D</tipo>

=======
            <descripcion>Descripción del juego</descripcion>
            <genero>Aventura</genero>
            <precio>80</precio>
            <tipo>2D</tipo>
            <categoria>01</categoria>
>>>>>>> eb8a0721894bf1a1ce89b4d3af93bf36aaf1ac21
        </juego>

        <juego id="C003" publicado="false">
            <nombre>Mario Kart</nombre>
<<<<<<< HEAD
            <descripcion> Descripción del juego </descripcion>
            <genero>Carreras</genero>
            <precio>50</precio>
            <tipo>2D</tipo>
=======
            <descripcion>Descripción del juego</descripcion>
            <genero>Carreras</genero>
            <precio>50</precio>
            <tipo>3D</tipo>
            <categoria>01</categoria>
>>>>>>> eb8a0721894bf1a1ce89b4d3af93bf36aaf1ac21
        </juego>

        <juego id="D004" publicado="true">
            <nombre>Call of Duty: Warzone</nombre>
<<<<<<< HEAD
            <descripcion> Descripción del juego </descripcion>
            <genero>Accion</genero>
            <precio>60</precio>
            <tipo>3D</tipo>
=======
            <descripcion>Descripción del juego</descripcion>
            <genero>Accion</genero>
            <precio>60</precio>
            <tipo>3D</tipo>
            <categoria>01</categoria>
>>>>>>> eb8a0721894bf1a1ce89b4d3af93bf36aaf1ac21
        </juego>

        <juego id="E005" publicado="false">
            <nombre>Minecraft</nombre>
<<<<<<< HEAD
            <descripcion> Descripción del juego</descripcion>
            <genero>Aventura</genero>
            <precio>25</precio>
            <tipo>3D</tipo>
=======
            <descripcion>Descripción del juego</descripcion>
            <genero>Aventura</genero>
            <precio>25</precio>
            <tipo>3D</tipo>
            <categoria>02</categoria>
>>>>>>> eb8a0721894bf1a1ce89b4d3af93bf36aaf1ac21
        </juego>

        <juego id="F006" publicado="true">
            <nombre>Assassin's Creed: Valhalla</nombre>
<<<<<<< HEAD
            <descripcion> Descripción del juego</descripcion>
            <genero>Estrategia</genero>
            <precio>70$</precio>
            <tipo>2D</tipo>
        </juego>
    </juegos>
    <generos>
        <generos id="01">Acción</generos>
        <generos id="02">Aventura</generos>
        <generos id="03">Carreras</generos>
        <generos id="04">Deportes</generos>
        <generos id="05">Estrategia</generos>
        <generos id="06">Simulación</generos>
        <generos id="07">Rol</generos>
        <generos id="08">Puzzle</generos>
        <generos id="09">Musical</generos>
        <generos id="10">Plataformas</generos>
    </generos>
</tienda>
=======
            <descripcion>Descripción del juego</descripcion>
            <genero>Accion</genero>
            <precio>70</precio>
            <tipo>2D</tipo>
            <categoria>02</categoria>
        </juego>
    </juegos>

     <!-- Información de las categorias -->
    <categorias>
        <categoria id="01">
            <nombre>Nacional</nombre>
        </categoria>
        <categoria id="02">
            <nombre>Internacional</nombre>
        </categoria>
    </categorias>
</tienda>
>>>>>>> eb8a0721894bf1a1ce89b4d3af93bf36aaf1ac21
